#!/usr/bin/perl

my $bTempDir;
if(-d "/tmp") {
    $bTempDir = 0;
} else {
    mkdir("/tmp");
    $bTempDir = 1;
}

my $rootdir = $ARGV[0];
my $outfile = $ARGV[1];
my $statsfile = $ARGV[2];
if($rootdir eq '')
{
    $rootdir = 'fs';
}
if($outfile eq '')
{
    $outfile = 'fsdata.c';
}
if($outfile eq '') {
open(OUTPUT, "> fsdata.c");

} else {
open(OUTPUT, "> " . $outfile);
}
if($statsfile eq '') {
open(STATSOUTPUT, "> fsdata-stats.c");

} else {
open(STATSOUTPUT, "> " . $statsfile);
}
if($rootdir eq '') {
chdir("fs");
} else {
chdir($rootdir);
}

print(OUTPUT "/* Generated automatically by ./makefsdata $ARGV[0] $ARGV[1] $ARGV[2] */\n\n");
print(OUTPUT "#include \"../".$statsfile."\"\n\n");

open(FILES, "find . -type f |");

while($file = <FILES>) {

    # Do not include files in CVS directories nor backup files.
    if($file =~ /(CVS|~)/) {
        next;
    }

    chop($file);

    open(HEADER, "> /tmp/header") || die $!;
    if($file =~ /404/) {
    print(HEADER "HTTP/1.1 404 File not found\r\n");
    } else {
    print(HEADER "HTTP/1.1 200 OK\r\n");
    }
    print(HEADER "Server: lwIP/1.2.0 (http://www.sics.se/~adam/lwip/)\r\n");
    if(($file =~ /\.html$/) || ($file =~ /\.htm$/)) {
    print(HEADER "Content-type: text/html\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif(($file =~ /\.shtml$/) || ($file =~ /\.shtm$/) ||
            ($file =~ /\.ssi$/)){
    print(HEADER "Content-type: text/html\r\n");
    print(HEADER "Cache-Control: no-cache\r\n");
    } elsif($file =~ /\.gif$/) {
    print(HEADER "Content-type: image/gif\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif($file =~ /\.png$/) {
    print(HEADER "Content-type: image/png\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif($file =~ /\.jpg$/) {
    print(HEADER "Content-type: image/jpeg\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif($file =~ /\.class$/) {
    print(HEADER "Content-type: application/octet-stream\r\n");
    } elsif($file =~ /\.ram$/) {
    print(HEADER "Content-type: audio/x-pn-realaudio\r\n");
    print(HEADER "Cache-Control: no-cache\r\n");
    } elsif($file =~ /\.bmp$/) {
    print(HEADER "Content-type: image/bmp\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif($file =~ /\.css$/) {
    print(HEADER "Content-type: text/css\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif($file =~ /\.js$/) {
    print(HEADER "Content-type: application/ecmascript\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } elsif($file =~ /\.js\.gz$/) {
    print(HEADER "Content-encoding: gzip\r\n");
    print(HEADER "Content-type: application/ecmascript\r\n");
    print(HEADER "Expires: Tue, 19 Jan 2038 03:14:06 GMT\r\n");
    } else {
    print(HEADER "Content-type: text/plain\r\n");
    print(HEADER "Cache-Control: no-cache\r\n");
    }
    print(HEADER "\r\n");
    close(HEADER);

    unless($file =~ /\.plain$/ || $file =~ /cgi/ || $file =~ /\.inc$/) {
    system("cat /tmp/header $file > /tmp/file");
    } else {
    system("cp $file /tmp/file");
    }

    open(FILE, "/tmp/file");
    unlink("/tmp/file");
    unlink("/tmp/header");

    $file =~ s/\.//;
    $fvar = $file;
    $fvar =~ s-/-_-g;
    $fvar =~ s-\\-_-g;
    $fvar =~ s-\.-_-g;
    print(OUTPUT "static const unsigned char data".$fvar."[] = {\n");
    print(OUTPUT "\t/* $file */\n\t");
    for($j = 0; $j < length($file); $j++) {
    printf(OUTPUT "%#02x, ", unpack("C", substr($file, $j, 1)));
    }
    printf(OUTPUT "0,\n");


    $i = 0;
    while(read(FILE, $data, 1)) {
        if($i == 0) {
            print(OUTPUT "\t");
        }
        printf(OUTPUT "%#02x, ", unpack("C", $data));
        $i++;
        if($i == 10) {
            print(OUTPUT "\n");
            $i = 0;
        }
    }
    print(OUTPUT "};\n\n");
    close(FILE);
    push(@fvars, $fvar);
    push(@files, $file);
}

for($i = 0; $i < @fvars; $i++) {
    $file = $files[$i];
    $fvar = $fvars[$i];

    if($i == 0) {
        $prevfile = "NULL";
    } else {
        $prevfile = "file" . $fvars[$i - 1];
    }
    print(OUTPUT "const struct fsdata_file file".$fvar."[] = {{$prevfile, data$fvar, ");
    print(OUTPUT "data$fvar + ". (length($file) + 1) .", ");
    print(OUTPUT "sizeof(data$fvar) - ". (length($file) + 1) ."}};\n\n");
}

print(STATSOUTPUT "/* Generated automatically by ./makefsdata $ARGV[0] $ARGV[1] $ARGV[2] */\n\n");
print(STATSOUTPUT "#ifndef _FSDATA_STATS_H_\n");
print(STATSOUTPUT "#define _FSDATA_STATS_H_\n\n");
print(STATSOUTPUT "#define FS_ROOT file$fvars[$i - 1]\n");
print(STATSOUTPUT "extern const struct fsdata_file FS_ROOT[];\n\n");
print(STATSOUTPUT "#define FS_NUMFILES $i\n\n");
print(STATSOUTPUT "#endif\n");

if($bTempDir eq 1) {
    unlink("/tmp/file");
    rmdir("/tmp");
}
