<center><b> CRI Power Control Computer </b></center>
<hr>
<a href="control.shtml">Control</a>
<b> | </b><a href="tasks.shtml">Task Stats</a>
<b> | </b><a href="runtime.shtml">Run Time Stats</a>
<b> | </b><a href="stats.shtml">TCP Stats</a>
<b> | </b><a href="tcp.shtml">Connections</a>
<b> | </b><a href="config.shtml">Config</a>
<b> | </b><a href="adc.shtml">ADC</a>
<b> | </b><a href="dio.shtml">I2C DIO</a>
<b> | </b><a href="proc_io.shtml">Proc I/O</a>
<hr>
